services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
