CREATE TABLE IF NOT EXISTS role (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    role_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- Insert Roles
INSERT INTO role (name, description)
VALUES ('USER', 'Default role');
INSERT INTO role (name, description)
VALUES ('ADMIN', 'System access');
-- Insert Admin
INSERT INTO users (
        username,
        email,
        first_name,
        last_name,
        password,
        role_id
    )
VALUES (
        'admin',
        'admin@sms.com',
        'Admin',
        'System',
        '$2a$10$D/X3X/y0.p/f.7.j/7.5.OuJ.5.h.u.3.v.5.l.5.s.5.w.5.y.5.',
        -- "password" als Passwort
        (
            SELECT id
            FROM role
            WHERE name = 'ADMIN'
        )
    ) ON CONFLICT (email) DO NOTHING;